### ISSUE TITLE
lapa

### ISSUE THREAD

**Issue by ahead** [karshina/Rozdilovi#35]
- по клику на кнопку
- больше интервал
- быстрее
- fade out после "дропа"
- не перекрывать летающими словами кнопку, дропать не долетая

**Comment by ybogdanov** [comment]
@maycry please make lapa sprite awesome `img/ghost_hand.png`
the shitty green one is the state when the hand is grabbing the word

**Comment by ahead** [comment]
@ybogdanov Юр, ты допилишь вот эти пункты?
- по клику на кнопку
- быстрее
- fade out после "дропа" (иначе не очевидно, где дропать)
- не перекрывать летающими словами кнопку, дропать не долетая (сейчас призраки иногда налазят на кнопку, и без click-through)
  спасибо )

**Comment by ybogdanov** [comment]
так сделал все жеж

**Comment by ybogdanov** [comment]
а по клику на кнопку не делал

**Comment by ybogdanov** [comment]
скорость сам можешь потюнить https://github.com/karshina/Rozdilovi/blob/gh-pages/js/main.js#L259
