### ISSUE TITLE
ghost positioning bug

### ISSUE THREAD

**Issue by ahead** [karshina/Rozdilovi#39]
призраки слева недолетают до середины круга, призраки справа перелетают ее и налазят на кнопку

**Comment by ybogdanov** [comment]
Это было пофикшено еще в момент добавления лапы, можешь перепроверить?

**Comment by ahead** [comment]
перепроверил, все равно есть
там картинка горизонтально не симметричная, а вычисления симметричные вроде

**Comment by ahead** [comment]
Yuriy Bogdanov [9:15 AM]
короче надо переверстать слова
так чтобы они были четко по центру слотов

**Comment by ybogdanov** [comment]
@ahead а кто их резал? Где макет?

**Comment by ahead** [comment]
@ybogdanov я проверил - порезаны они правильно, картинки одинаковой ширины и все слова по центру. но дивы слотов шире чем картинки со словами и в них картинки не центрируются. можно добавить в класс .word text-align:center и подвинуть координаты всех слотов во всех разрешениях влево на одинаковую величину

**Comment by ybogdanov** [comment]
@ahead it's because of this https://github.com/karshina/Rozdilovi/blob/gh-pages/css/main.css#L233

**Comment by ybogdanov** [comment]
@ahead centered the words, please check if it helped.

**Comment by ahead** [comment]
@ybogdanov оно-то помогло, но - см мой коммент выше - теперь все слова сдвинуты относительно круга, и их слоты нужно подвинуть влево на одинаковую величину. это немного муторно, учитывая responsive. но я подвигаю

**Comment by ybogdanov** [comment]
@ahead please check if it became better.

**Comment by ahead** [comment]
@ybogdanov it became better on the left side but worse on the right side
