### ISSUE TITLE
Design the Афіша page

### ISSUE THREAD

**Issue by ahead** [karshina/Rozdilovi#50]
Анонси запланованих подій можуть включати таку інформацію:
- дата, час
- місце (місто і зала)
- вартість квитків (або "вхід вільний", або за попередньою реєстрацією)
- посилання на купівлю квитків або форму реєстрації - опціонально
- коментар (наприклад, особливий склад або виступ в рамках фестивалю) - опціонально
- афіша - опціонально (приклади афіш - тут: https://www.dropbox.com/sh/vtymncvdtzvcs91/AABjYKdP41gaCjy7VvA8sH0ja?dl=0)
- посилання на подію в соцмережі - опціонально

Список розділений на:
- Майбутні події - sorty by date Asc
- Минулі події (дата, місце, (коментар), (афіша) + 0..N посилань на публікації про виступ) - sort by date Desc

**Comment by maycry** [comment]
Дим, сколько этих постеров будет на странице примерно? Мне это нужно знать, что понимать как ее верстать. Еще можно прошедшие события не удалять, а архивировать и помечать соответствующе (вожможно делать бледными).

**Comment by ahead** [comment]
в феврале-марте будет тур - наверное, порядка 10 выступлений. 
их нужно будет показать на странице одновременно. 
скорее всего, в этом же году не будет больше выступлений. разве что одно-два-три еще.
прошедшие было бы хорошо архивировать, да.

что важно - постер, наверное, будет один на весь тур - так было в прошлый раз, например. я упустил это

**Comment by maycry** [comment]
https://dl.dropboxusercontent.com/u/15072803/Rozdilovi-afisha.jpg
