### ISSUE TITLE
Video launch on mobile

### ISSUE THREAD

**Issue by ahead** [karshina/Rozdilovi#51]
autoplay doesn't work
button is not responsive enough
links from cards work ok

**Comment by ybogdanov** [comment]
Unfortunately, autoplay cannot be done on iOS devices (iPhone, iPad, iPod touch) and Android.
http://stackoverflow.com/questions/15090782/youtube-autoplay-not-working-on-mobile-devices-with-embedded-html5-player

I will disable autoplay on mobile devices, so users will have to hit the play button.

**Comment by ybogdanov** [comment]
(not deployed)
