### ISSUE TITLE
Cards on mobile

### ISSUE THREAD

**Issue by ahead** [karshina/Rozdilovi#52]
displayed on plane icon click (when video is stopped)
- from card links

**Comment by ybogdanov** [comment]
See https://github.com/karshina/Rozdilovi/commit/a255301461279169746826a4acfd31da7341534f#diff-211cf1cc161ec8579aa99a3b2642d109R224 there is another option for card markup that does not take fullscreen, though I prefer the fullscreen one. Overall it looks not so good, but I don't have ideas of how to improve it – feel free to play with markup.

You can debug the markup with Safari, see the instruction here https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

The key places where you can tweak sizes and offests are:
https://github.com/karshina/Rozdilovi/blob/a255301461279169746826a4acfd31da7341534f/css/main.css#L745
https://github.com/karshina/Rozdilovi/blob/a255301461279169746826a4acfd31da7341534f/css/share.css#L190
https://github.com/karshina/Rozdilovi/blob/a255301461279169746826a4acfd31da7341534f/js/video.js#L370
